pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "TAL-Patch"
include ":loader"   // Java hook 逻辑 → loader.dex
include ":zygisk"   // Zygisk native 注入器 → libtalpatch.so
