plugins {
    id "com.android.application"
}
android {
    namespace "com.kevin233.talpad.hook"
    compileSdk 34
    defaultConfig {
        applicationId "com.kevin233.talpad.hook"
        minSdk 33
        targetSdk 34
        versionCode 220
        versionName "2.2.0"
    }
    buildTypes {
        release {
            minifyEnabled true
            shrinkResources false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.debug
        }
        debug {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}
dependencies {
    compileOnly "io.github.libxposed:api:101.0.1"
    implementation "androidx.appcompat:appcompat:1.7.0"
    implementation "com.google.android.material:material:1.12.0"
}
